In [1]:
"""
Purpose: To show how to 
a) decompose a neuron with the analysis into a neuron object
b) compress the object into a smaller data representation for storage
c) decompress the object back into the original object (using the original mesh)
d) make sure the decompressed version matches the original

"""

'\nPurpose: To show how to \na) decompose a neuron with the analysis into a neuron object\nb) compress the object into a smaller data representation for storage\nc) decompress the object back into the original object (using the original mesh)\nd) make sure the decompressed version matches the original\n\n'

In [2]:
from os import sys
sys.path.append("../meshAfterParty")

In [3]:
import neuron
import system_utils as su
from importlib import reload
import trimesh_utils as tu
import skeleton_utils as sk
from pathlib import Path
import trimesh
import neuron_utils as nru

# Step 1: Decomposition

In [4]:
segment_id = 12345
current_mesh_file = "multi_soma_example.off"
description="2_soma_practice_decompress"

double_soma_neuron = tu.load_mesh_no_processing(current_mesh_file)
sk.graph_skeleton_and_mesh(other_meshes = [double_soma_neuron])

/usr/local/lib/python3.6/dist-packages/traittypes/traittypes.py:101: UserWarning: Given trait value dtype "float64" does not match required type "float64". A coerced copy has been created.
  np.dtype(self.dtype).name))


In [5]:
nru = reload(nru)
neuron = reload(neuron)
double_neuron = neuron.Neuron(
    mesh=double_soma_neuron,
    segment_id=segment_id,
    description=description
                         )

--- 0) Having to preprocess the Neuron becuase no preprocessed data
Please wait this could take a while.....


--- 0) Total time for preprocessing: 1144.5990407466888




--- 1) Finished unpacking preprocessed materials: 7.867813110351562e-06
total_edges = [['S0', 'L0'], ['S0', 'L1'], ['S0', 'L2'], ['S0', 'L3'], ['S0', 'L5'], ['S0', 'L10'], ['S1', 'L1'], ['S1', 'L4'], ['S1', 'L6'], ['S1', 'L7'], ['S1', 'L8'], ['S1', 'L9']]
--- 2) Finished creating neuron connectivity graph: 0.00015974044799804688
Having to generate soma_meshes_face_idx because none in preprocessed data
--- 3a) Finshed generating soma_meshes_face_idx: 4.575231075286865
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 6330
xvfb-run -n 6330 -s "-screen 0 800x600x24" meshlabserver $@  -i /examples/Poisson_temp/neuron_197357.off -o /examples/Poisson_temp/neuron_197357_poisson.off -s /examples/Poisson_temp/poisson_694884.mls


face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!


removed temporary input file: /examples/Poisson_temp/neuron_197357.off
removed temporary output file: /examples/Poisson_temp/neuron_197357_poisson.off
/examples/Poisson_temp/poisson_694884.mls is being deleted....
Using Poisson Surface Reconstruction to make mesh watertight
IN INPUT FILE VALIDATION LOOP
LEAVING LOOP, MESH VALIDATED
Using port = 9000
xvfb-run -n 9000 -s "-screen 0 800x600x24" meshlabserver $@  -i /examples/Poisson_temp/neuron_669593.off -o /examples/Poisson_temp/neuron_669593_poisson.off -s /examples/Poisson_temp/poisson_793210.mls


face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!
face_normals all zero, ignoring!


removed temporary input file: /examples/Poisson_temp/neuron_669593.off
removed temporary output file: /examples/Poisson_temp/neuron_669593_poisson.off
/examples/Poisson_temp/poisson_793210.mls is being deleted....
--- 3) Finshed generating soma objects and adding them to concept graph: 19.42961311340332
--- 4a) Finshed generating curr_limb_meshes_face_idx: 15.901102304458618
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
There are loops to resolve and 'no_cycles' parameters set requires us to fix eliminate them
Using mesh_widths for resolving loops
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
No cycles to fix
checking and resolving cycles
There are loops to resolve and 'no_cycles' parameters set requires us to fix eliminate them
Using mesh_widths for resolving loops
checking and resolvi

In [6]:
import trimesh
trimesh.__version__

'3.6.15'

# Step 2: Compressing a Neuron

In [7]:
# Rerunning compression analysis on interneurons
import neuron_utils as nru
su = reload(su)
nru = reload(nru)
location=Path("test_pickle")
location.mkdir(exist_ok=True,parents=True)

compressed_file = nru.save_compressed_neuron(double_neuron,output_folder=location,return_file_path=True)

Total time for soma meshes compression = 4.629509925842285
Total time for insignificant_limbs,inside_pieces,non_soma_touching_meshes compression = 8.04843282699585
Total time for limb_meshes compression = 16.623494148254395
    Starting Limb Correspondence Compression



Total time for new_limb_correspondence compression = 174.2241473197937
Total time for compression = 203.52652525901794
Saved object at /examples/test_pickle/12345_2_soma_practice_decompress.pbz2
File size is 3.488432 MB


---Finished outputing neuron at location: /examples/test_pickle/12345_2_soma_practice_decompress---


#  Step 3: Decompressing a Neuron

In [8]:
su = reload(su)
neuron = reload(neuron)
nru=reload(nru)
from tqdm.notebook import tqdm


recovered_neuron = nru.decompress_neuron(filepath=compressed_file,
                  original_mesh=double_neuron.mesh)




------Working on limb 0 -------
inside loop len(curr_limb_divided_meshes) = 79 len(curr_limb_divided_skeletons) = 79
--- Working on soma_idx: 0----
Total time for filtering periphery meshes = 1.4367609024047852
Total time for mesh mapping: 1.7532508373260498
Total time for mesh mapping: 0.4591221809387207
touching_pieces = [48]
Total time for mesh connectivity = 2.2279462814331055
Touching piece endpoints = [[756812.  947032.  873832. ]
 [758776.5 949135.2 872731.4]]
inside inner loop len(curr_limb_divided_skeletons) = 79
closest_endpoint = [758776.5 949135.2 872731.4]
Starting_edge inside branches_to_conept = [[756812.  947032.  873832. ]
 [758776.5 949135.2 872731.4]]
At the start, starting_node (in terms of the skeleton, that shouldn't match the starting edge) = [53]
printing out current edge:
[[758776.5 949135.2 872731.4]
 [756812.  947032.  873832. ]]
edge_endpoints_to_process was empty so exiting loop after 79 iterations
starting_node in concept map (that should match the star

# Step 4: Checking that decompressed neuron object and origianl object were the same

In [9]:
recovered_neuron == double_neuron

True